image: node:lts

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm install
    - npx hardhat coverage --testfiles "test/*.js"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  coverage: '/Lines\s+: \d+\.\d+%/'
